// <auto-generated />
using System;
using AppBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250305041409_CreateConnectingFlightsView")]
    partial class CreateConnectingFlightsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppBackend.Models.CombineFlight", b =>
                {
                    b.Property<string>("ArriveAirport")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ArriveAirport");

                    b.Property<DateTime>("ArriveDateTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ArriveDateTime");

                    b.Property<string>("DepartAirport")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("DepartAirport");

                    b.Property<DateTime>("DepartDateTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DepartDateTime");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("FlightNumber");

                    b.Property<string>("FlightSource")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("flight_source");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.ToTable((string)null);

                    b.ToView("combined_flights", (string)null);
                });

            modelBuilder.Entity("AppBackend.Models.Deltas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArriveAirport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ArriveDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartAirport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DepartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Deltas");
                });

            modelBuilder.Entity("AppBackend.Models.SouthWests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArriveAirport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ArriveDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartAirport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DepartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SouthWests");
                });
#pragma warning restore 612, 618
        }
    }
}
